language : python
python:
    - "3.6"
services:
 - postgresql

install:
 - pip install -r requirements.txt
 - pip install coveralls
before_script:
 - source ./.travis.sh
 - psql -c "create role peshy with superuser login password 'admin';" -U postgres
 - psql -c 'create database politico;' -U postgres
 - psql -c 'alter database politico owner to peshy' -U postgres
 - psql -c 'create database test_andela;' -U postgres
 - psql -c 'alter database test_andela owner to peshy' -U postgres


script:
 - source ./.travis.sh
 - pytest -v --cov=app/tests

after_script:
 - coveralls

after_success:
 - coveralls